### ISSUE TITLE
Login with 2FA (yubikey) on a android phone with the android app

### ISSUE THREAD

**Issue by larglarg** [nextcloud/twofactor_webauthn#311]
### Steps to reproduce
1.Login normaly to your nextcloud and get to the point where u are asked for the 2fa 
2.Trying to login with a yubikey 5c with the android app
3.

### Expected behaviour
You shut be logged in

### Actual behaviour
the app chrashed and showning this error:
### Cause of error
```java
Exception in thread "main" java.lang.RuntimeException: Error receiving broadcast Intent { act=de.cotech.hw.ACTION_USB flg=0x10 pkg=com.nextcloud.client } in de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@c0ef25f
    at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1572)
    at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:236)
    at android.app.ActivityThread.main(ActivityThread.java:7861)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'int android.hardware.usb.UsbDevice.getInterfaceCount()' on a null object reference
    at de.cotech.hw.internal.transport.usb.UsbDeviceManager.isRelevantDevice(UsbDeviceManager.java:163)
    at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher.handleConnectedUsbDevice(UsbConnectionDispatcher.java:90)
    at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher.access$100(UsbConnectionDispatcher.java:45)
    at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1.onReceive(UsbConnectionDispatcher.java:77)
    at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1562)
    at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:236)
    at android.app.ActivityThread.main(ActivityThread.java:7861)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30230090`
* Build flavor: `gplay`

### Device information
* Brand: `Redmi`
* Device: `joyeuse`
* Model: `Redmi Note 9 Pro`
* Id: `RKQ1.200826.002`
* Product: `joyeuse_eea`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `V12.5.8.0.RJZEUXM`

On my dekstop pc it is working just fine. 
With firefox on my smartphone as well. 
An alsow with the app if the accound dose not have 2fa setup. 

the PHP version is 8.1 
the server is runing on a apache2 server 
and is accesed via a reversproxy nginx. 
in the errors only the faild login is listed without further informations

**Comment by ChristophWurst** [comment]
> ```java
> de.cotech.hw.ACTION_USB
> ```

@AlvaroBrey do we launch this intent from the Nextcloud Files Android app? I'm not sure if I read the trace information correctly.

**Comment by AlvaroBrey** [comment]
> > ```java
> > de.cotech.hw.ACTION_USB
> > ```
> 
> @AlvaroBrey do we launch this intent from the Nextcloud Files Android app? I'm not sure if I read the trace information correctly.

Yes, it's likely launched by this lib: https://github.com/cotechde/hwsecurity, which we use.

**Comment by larglarg** [comment]
so I have to report the bug there ?

**Comment by AlvaroBrey** [comment]
> so I have to report the bug there ?

No, I'll transfer this to the android app repo. Sorry!
