### ISSUE TITLE
Personal settings UI is broken on Nextcloud 28

### ISSUE THREAD

**Issue by st3iny** [nextcloud/twofactor_webauthn#494]
### Steps to reproduce
1. Enroll a new device or try to toggle an existing one.

### Expected behaviour

The action should be executed. On older sessions, the user should be asked for a password confirmation.

### Actual behaviour

Nothing happens.

### Problem

A password confirmation is requested for both actions and the installed version of `@nextcloud/password-confirmation` is not compatible with Nextcloud 28.

![grafik](https://github.com/nextcloud/twofactor_webauthn/assets/1479486/d03d114f-051f-496c-9693-b1fd57f9999f)

Ref https://github.com/nextcloud-libraries/nextcloud-password-confirmation#versions-compatibility

**Comment by ChristophWurst** [comment]
Same as https://github.com/nextcloud/server/issues/41760#issuecomment-1827815550?

**Comment by st3iny** [comment]
This could be it. The incompatibility I mentioned was just a wild guess.

Well, the fix mentioned there wasn't backported so I'm gonna have to migrate this app to the default versioning scheme :clown_face: (and release ASAP).

Ref https://github.com/nextcloud-libraries/nextcloud-password-confirmation/pull/666

---

Browser log:
```
TypeError: Cannot read properties of undefined (reading '$el')
    at o.<anonymous> (index.mjs:35:24)
    at Array.<anonymous> (vue.runtime.esm.js:3143:20)
    at Mt (vue.runtime.esm.js:3065:16)
```

**Comment by st3iny** [comment]
Well well, the app works without `@nextcloud/vue` 8 and `@nextcloud/password-confirmation` 5. I tested all the way down to Nextcloud 25 so we can keep a single branch for now.
